language: node_js
node_js: 
  - "8"

cache:
  directories:
    - node_modules

install: 
  - cd $TRAVIS_BUILD_DIR/client
  - npm install
  - cd $TRAVIS_BUILD_DIR/server
  - npm install

script: 
  # Client
  - cd $TRAVIS_BUILD_DIR/client
  - npm run build:prod
  # - npm run test
  # Server
  - cd $TRAVIS_BUILD_DIR/server 
  - npm run build
  # - npm run test

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod ugo+x ./docker-push.sh
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "CURRENT_BRANCH=$BRANCH"

deploy:
  - provider: script
    skip_cleanup: true
    script: ./docker-push.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./docker-push.sh
    on:
      branch: dev
  - provider: script
    skip_cleanup: true
    script: ./docker-push.sh
    on:
      tags: true