language: node_js
node_js: 
  - "8"

install: 
  - npm install
  - npm install -g typescript@2.4.2
  - npm install -g jest@20.0.4
  - npm install -g less@2.7.2

script: 
  - npm run build-server
  - npm run build-client
  - npm run less
  - npm run build-test