language: node_js
node_js: 
  - "8"

install: 
  - cd $TRAVIS_BUILD_DIR/server
  - yarn install
  - cd $TRAVIS_BUILD_DIR/client
  - yarn install
script: 
  # Client
  - cd $TRAVIS_BUILD_DIR/client
  - yarn run build
  - yarn run less
#  - yarn run test
  # Server
  - cd $TRAVIS_BUILD_DIR/server
  - yarn run build
#  - yarn run test

after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod ugo+x ./docker-push.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./docker-push.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./docker-push.sh
    on:
      branch: dev
  - provider: script
    skip_cleanup: true
    script: ./docker-push.sh
    on:
      branch: feat/docker-compose #testing