version: "3.2"

services:
  sg:
    build: .
    image: osucass/scoring-guide:dev
    environment: 
      - sampleItemsApi=http://siw
      - itemViewerServiceApi:http://localhost:8174
    ports:
      - "80:3000"
    depends_on: 
      - "siw"
      - "ivs"
    networks: 
      - itemsampler
  siw: 
    image: osucass/sampleitemscode:scoreguide
    ports: 
      - "5000:80"
    volumes: 
      - /c/content:/app/content
    environment:
      - SettingsConfig:ItemViewerServiceURL=http://localhost:8174
    depends_on: 
      - "ivs"
    networks: 
      itemsampler:
        aliases: 
          - siw
  ivs: 
    image: osucass/itemviewerservicecode:1.1.3
    ports: 
      - "8174:8080"
    volumes: 
      - /c/content:/home/tomcat7/content

networks: 
  itemsampler: